---
title: "Pivoting Greenland and Alaska"
author: "Emma Vejcik"
date: "4/13/2022"
output: html_document
---

```{r}
library(dplyr)
library(tidyverse)
```

# Greenland Wrangling

```{r}
greenland_sites <- greenland %>% 
  select(sample_id, bsi)
```

```{r}
greenland_wavenumbers <- greenland %>% 
  pivot_longer(
    3:3699,
    names_to = "Wavenumbers",
    values_to = "Value"
  )%>%
  select(-c(bsi))
```

```{r}
greenland_long <- greenland %>% 
  pivot_longer(
    3:3699,
    names_to = "Wavenumbers",
    values_to = "Value"
  )
```


# Alaska Wrangling

```{r}
alaska_sites <- alaskaWetChemAbsorbance %>% 
  select(sample_id, bsi)
```

```{r}
alaska_wavenumbers <- alaskaWetChemAbsorbance %>% 
  pivot_longer(
    3:1884,
    names_to = "Wavenumbers",
    values_to = "Value"
  )%>%
  select(-c(bsi))
```


# Joining All in One Table 

```{r}
alaska_all <- full_join(alaska_sites,alaska_wavenumbers, by = "sample_id")
```

```{r}
greenland_all <- full_join(greenland_sites,greenland_wavenumbers, by = "sample_id")
```

```{r}
greenland_unpivot <- greenland_all %>%
  pivot_wider(names_from = "Wavenumbers",
              values_from = "Value") 
```














